development:
  adapter: postgresql
  database: tutorial_app_development
  host: localhost

test:
  adapter: postgresql
  database: tutorial_app_test
  host: localhost

production:
  adapter: postgresql
  database: tutorial_app_production
  host: localhost
